#include <iostream>
#include <iomanip>
#include <vector>
#include <memory>

#include <TGeoManager.h>
#include <TGeoNode.h>
#include <TVector3.h>
#include <TLorentzVector.h>
#include <TParticlePDG.h>
#include <TMath.h>

#include "TG4HitBase.hxx"
#include "TG4PrimaryVertex.hxx"
#include "TG4PrimaryParticle.hxx"
#include "TOADatabase.hxx"
#include "HEPUnits.hxx"

#include "exampleSelector.h"

Bool_t exampleSelector::Process(Int_t entry) {
    std::cout << "######################################################" 
              << std::endl;
    fChain->GetTree()->GetEntry(entry);
    
    // This is an example of how to get at various pieces of information in an
    // ND280MC event file.  You should probably delete most of this from your
    // analysis. 
    std::cout << "Entry " << entry 
              << " is for event ID " << ND280Event->GetEventID() 
              << " with reaction code " << ND280Event->GetReactionCode()
              << std::endl;
    
    /////////////////////////////////////////////////////////
    // Get the location of the primary vertex, and find which volume contains
    // the vertex. .
    TBorrowed<TG4PrimaryVertexContainer*> primaries 
        = ND280Event->Get<TG4PrimaryVertexContainer>("truth/G4PrimVertex00");
    const TLorentzVector& vertex = primaries->front().GetPosition();

    TGeoManager* geom = TOADatabase::Get().Geometry();
    TGeoNode* vertexNode 
        = geom->FindNode(vertex.X(), vertex.Y(), vertex.Z());
    int geoNodeID = geom->GetCurrentNodeId();
    std::cout << " The vertex is at (" << vertex.X()/unit::cm << " cm"
              << "," << vertex.Y()/unit::cm << " cm" 
              << "," << vertex.Z()/unit::cm << " cm"
              << "," << vertex.T()/unit::ns << " ns)"
              << "    Node ID " << geoNodeID
              << std::endl;
    std::cout << "    The current path is " << geom->GetPath()
              << std::endl;
    std::cout << "     which is is in " << vertexNode->GetName() 
              << " copy nb." << vertexNode->GetNumber()
              << std::endl;

    ////////////////////////////////////////////////////////
    // To find out which particles were tracked, you can look at the
    // TG4PrimaryParticles associated with the primary vertex.
    const TG4PrimaryParticleContainer& particles 
        = primaries->front().GetPrimaryParticles();
    for (TG4PrimaryParticleContainer::const_iterator p = particles.begin();
         p != particles.end();
         ++p) {
        // The particle type information uses the ROOT particle data base.
        // Notice the idiosyncrasy that the charge is in quark charge (units
        // of |e|/3, so an electron as a charge of 3) and the mass is in GeV. 
        const TParticlePDG* particleInfo = p->GetParticle();
        std::cout << "   Tracked a " << particleInfo->GetName() 
                  << " with mass " << particleInfo->Mass()<<" GeV/c^2"
                  << " and charge " << particleInfo->Charge()
                  << std::endl;
        // The particle momentum, and direction can be found using
        // GetMomentum().  The momentum is in units of MeV/c.
        const TLorentzVector& mom = p->GetMomentum();
        std::cout << "     The energy is " << mom.E()/unit::MeV << " MeV"
                  << ", the mass is " << mom.M()/unit::MeV << " MeV/c^2"
                  << ", the momentum is " << mom.P()/unit::MeV << " MeV/c"
                  << std::endl;
        TVector3 dir = mom.Vect().Unit();
        std::cout << "     The direction is "
                  << "(" << dir.X()
                  << "," << dir.Y()
                  << "," << dir.Z() << ")"
                  << std::endl;
    }


    ////////////////////////////////////////////////////////////
    // Get the hits generated by G4.  These hits are 
    TBorrowed<TDataVector*> g4Hits 
        = ND280Event->Get<TDataVector>("truth/g4Hits");
    std::cout << "There are " << g4Hits->size() 
              << " containers of hits in the event"
              << std::endl;

    for (TDataVector::const_iterator hits = g4Hits->begin();
         hits != g4Hits->end();
         ++hits) {
        std::cout << "  Hits " << (*hits)->GetFullName() << std::endl;
        TBorrowed<const TG4HitBaseContainer*> hitCont 
            = dynamic_cast<const TG4HitBaseContainer*>(*hits);
        for (TG4HitBaseContainer::const_iterator h = hitCont->begin();
             h != hitCont->end();
             ++h) {
            // Get the hit information.
            TVector3 pos = h->GetVolumePosition();
            std::cout << "    hit " << h->GetGeoNodeID()
                      << " at (" << pos.X()/unit::cm << " cm"
                      << "," << pos.Y()/unit::cm << " cm"
                      << "," << pos.Z()/unit::cm << " cm" << ")"
                      << " with " << h->GetEnergyDeposit()/unit::MeV << " MeV"
                      << " from " << h->GetPrimaryID()
                      << std::endl;

            // Find the current volume using the node ID
            geom->CdNode(h->GetGeoNodeID());
            double local[3] = {0,0,0};
            double master[3];
            geom->LocalToMaster(local,master);
            std::cout << "      The volume is centered at " 
                      << "(" << master[0]/unit::cm << " cm"
                      << "," << master[1]/unit::cm << " cm"
                      << "," << master[2]/unit::cm << " cm" << ")"
                      << std::endl;

            // Find the current volume using the node position.  You should
            // usually use geom->CdNode(id) as above.
            geom->FindNode(pos.X(), pos.Y(), pos.Z());
            int geoNodeID = geom->GetCurrentNodeId();
            std::cout << "      " << geoNodeID
                      << " is " << geom->GetPath()
                      << std::endl;
        }
    }

    return kTRUE;
}
