#include <vector>

#include <TGeoManager.h>
#include <TGeoNode.h>
#include <TVector3.h>
#include <TLorentzVector.h>
#include <TParticlePDG.h>
#include <TMath.h>
#include <TCanvas.h>

#include "g4HitBaseSelector.h"
#include "HEPUnits.hxx"

void g4HitBaseSelector::Begin(TTree* tree) {
    fTPCz = new TH1F("TPCz",
                     "Z VolumePosition of G4BaseHit objects from TPC",
                     1000, -500, 500);
    fP0Dz = new TH1F("P0Dz",
                     "Z VolumePosition of G4BaseHit objects from P0D",
                     1000, -500, 500);
    fFGDz = new TH1F("FGDz",
                     "Z VolumePosition of G4BaseHit objects from FGD",
                     1000, -500, 500);
    fECALz = new TH1F("ECALz",
                      "Z VolumePosition of G4BaseHit objects from ECAL",
                     1000, -500, 500);
}

Bool_t g4HitBaseSelector::Process(Int_t entry) {
    std::cout << "######################################################" 
              << std::endl;
    fChain->GetTree()->GetEntry(entry);
    
    std::cout << "Entry " << entry 
              << " is for event ID " << ND280Event->GetEventID() 
              << " with reaction code " << ND280Event->GetReactionCode()
              << std::endl;
    
    ////////////////////////////////////////////////////////////
    // Get the hits generated by G4.  These hits are 
    TBorrowed<const TG4HitBaseContainer*> hitCont 
        = ND280Event->Get<TG4HitBaseContainer>("truth/g4Hits/tpc");
    std::cout << "Hits in " << hitCont->GetFullName()
              << std::endl;
    for (TG4HitBaseContainer::const_iterator h = hitCont->begin();
         h != hitCont->end();
         ++h) {
        // Get the hit information.
        TVector3 pos = h->GetVolumePosition();
        fTPCz->Fill(pos.Z()/unit::cm);
    }

    hitCont = ND280Event->Get<TG4HitBaseContainer>("truth/g4Hits/p0d");
    std::cout << "Hits in " << hitCont->GetFullName()
              << std::endl;
    for (TG4HitBaseContainer::const_iterator h = hitCont->begin();
         h != hitCont->end();
         ++h) {
        // Get the hit information.
        TVector3 pos = h->GetVolumePosition();
        fP0Dz->Fill(pos.Z()/unit::cm);
    }

    hitCont = ND280Event->Get<TG4HitBaseContainer>("truth/g4Hits/fgd");
    std::cout << "Hits in " << hitCont->GetFullName()
              << std::endl;
    for (TG4HitBaseContainer::const_iterator h = hitCont->begin();
         h != hitCont->end();
         ++h) {
        // Get the hit information.
        TVector3 pos = h->GetVolumePosition();
        fFGDz->Fill(pos.Z()/unit::cm);
    }

    hitCont = ND280Event->Get<TG4HitBaseContainer>("truth/g4Hits/ecal");
    std::cout << "Hits in " << hitCont->GetFullName()
              << std::endl;
    for (TG4HitBaseContainer::const_iterator h = hitCont->begin();
         h != hitCont->end();
         ++h) {
        // Get the hit information.
        TVector3 pos = h->GetVolumePosition();
        fECALz->Fill(pos.Z()/unit::cm);
    }

    return kTRUE;
}

void g4HitBaseSelector::Terminate(void) {
    TFile* output = new TFile("g4HitBase.root","RECREATE");
    if (!output->IsOpen()) return;

    fTPCz->Write();
    fP0Dz->Write();
    fFGDz->Write();
    fECALz->Write();

    output->Close();
}
