#! /bin/bash
#
# This is run without arguments.

# The location of the input files.
if [ ${GEOMFILES}x == x ]; then
    GEOMFILES=${CAPTAINPOLICYMIRROR}/files/geometry
fi

# This directory should ALWAYS exist, but check anyway.
if [ ! -d ${CAPTEVENTROOT} ]; then
    echo captain-get-geometry: captEvent directory is missing!
    echo    where is: ${CAPTEVENTROOT}
    exit 1
fi
cd ${CAPTEVENTROOT}

# This directory won't exist when the package is checkout the first  time.
if [ ! -d ${CAPTEVENTROOT}/${CAPTEVENTCONFIG} ]; then
    mkdir ${CAPTEVENTCONFIG}
fi
cd ${CAPTEVENTCONFIG}

for file in ${GEOMFILES}/*.root; do
    if [ -f ${file} ]; then
	ln -s ${file} `basename ${file}` >& /dev/null
    fi
done

echo Geometries up to date
