#ifndef TFGDmcDigit_hxx_seen
#define TFGDmcDigit_hxx_seen

#include <TFGDDigit.hxx>
#include <TMCDigit.hxx>

namespace ND {
    class TFGDmcDigit;
};

/// A class to hold FGD digits generated by the MC.  This inherits all of it's
/// functionality from TFGDDigit and TMCDigit.
class ND::TFGDmcDigit : public TFGDDigit, public TMCDigit {
public:

    TFGDmcDigit ();
    virtual ~TFGDmcDigit();

    /// Construct a digit for a particular channel
    TFGDmcDigit(ND::TChannelId chan, 
                short startTime, short pulseTime, short pulseCharge, 
                std::vector<unsigned short> adcs,
                short dataType,
                const ND::TMCDigit::ContributorContainer& contrib);

    ClassDef(TFGDmcDigit,2);
};
#endif
