#ifndef TMCDigit_hxx_seen
#define TMCDigit_hxx_seen

#include <vector>
#include <TROOT.h>

namespace ND {
    class TMCDigit;
    class TG4VHit;
};

/// An abstract base class for digits generated by the MC.  This is multiply
/// inherited by objects for each of the detector digit types.
class ND::TMCDigit {
public:
    typedef std::vector<TG4VHit*> ContributorContainer;

    TMCDigit ();
    virtual ~TMCDigit();

    /// Construct a digit for a particular channel and cycle number.
    explicit TMCDigit(const ND::TMCDigit::ContributorContainer& contrib);

    /// Return the MC information for the raw MC hits that contributed to this
    /// digit.
    virtual const ContributorContainer& GetContributors() const {
        return fContributors;
    }
    
private: 
    /// The MC hits that contributed to this digit.
    ContributorContainer fContributors;

};
#endif
