#ifndef TPulseMCDigit_hxx_seen
#define TPulseMCDigit_hxx_seen

#include <TPulseDigit.hxx>
#include <TMCDigit.hxx>

namespace CP {
    class TPulseMCDigit;
};

/// A class to hold FADC digits generated by the MC.  This inherits all of it's
/// functionality form TPulseDigit and TMCDigit.
class CP::TPulseMCDigit : public TPulseDigit, public TMCDigit {
public:

    TPulseMCDigit ();
    virtual ~TPulseMCDigit();

    /// Construct a digit for a particular channel.  See the documentation for
    /// CP::TPulseDigit for details.  The contrib container is documented in
    /// CP::TMCDigit.
    TPulseMCDigit(CP::TChannelId chan, 
                  int first, 
                  const CP::TPulseDigit::Vector& adcs,
                  const CP::TMCDigit::ContributorContainer& contrib);

    /// Construct a digit for a particular channel.  See the documentation for
    /// CP::TPulseDigit for details.  The contrib and info containers are
    /// documented in CP::TMCDigit.
    TPulseMCDigit(CP::TChannelId chan, 
                  int first, 
                  const CP::TPulseDigit::Vector& adcs,
                  const CP::TMCDigit::ContributorContainer& contrib,
                  const CP::TMCDigit::InfoContainer& info);

    ClassDef(TPulseMCDigit,3);
};
#endif
