#ifndef TTPCmcDigit_hxx_seen
#define TTPCmcDigit_hxx_seen

#include <TTPCDigit.hxx>
#include <TMCDigit.hxx>

namespace CP {
    class TTPCmcDigit;
};

/// A class to hold TPC digits generated by the MC.  This inherits all of it's
/// functionality form TTPCDigit and TMCDigit.
class CP::TTPCmcDigit : public TTPCDigit, public TMCDigit {
public:

    TTPCmcDigit ();
    virtual ~TTPCmcDigit();

    /// Construct a digit for a particular channel.  See the documentation for
    /// CP::TTPCDigit for details.  The contrib container is documented in
    /// CP::TMCDigit.
    TTPCmcDigit(CP::TChannelId chan, 
                int first, 
                const CP::TTPCDigit::Vector& adcs,
                const CP::TMCDigit::ContributorContainer& contrib);

    ClassDef(TTPCmcDigit,2);
};
#endif
