#ifndef TTFBmcDigit_hxx_seen
#define TTFBmcDigit_hxx_seen

#include <TTFBDigit.hxx>
#include <TMCDigit.hxx>

namespace CP {
    class TTFBmcDigit;
};

/// A class to hold TFB digits generated by the MC.  This inherits all of it's
/// functionality from TTFBDigit and TMCDigit.
class CP::TTFBmcDigit : public TTFBDigit, public TMCDigit {
public:

    TTFBmcDigit ();
    virtual ~TTFBmcDigit();

    /// Construct a digit for a particular channel and cycle number.
    TTFBmcDigit(CP::TChannelId chan, int highGainADC, 
		int lowGainADC, unsigned int timeCounter,
		int timeQuad, bool timeDiscriminator,
                const CP::TMCDigit::ContributorContainer& contrib);

    ClassDef(TTFBmcDigit,1);
};
#endif
