#ifndef TTPCmcDigit_hxx_seen
#define TTPCmcDigit_hxx_seen

#include <TTPCDigit.hxx>
#include <TMCDigit.hxx>

namespace CP {
    class TTPCmcDigit;
};

/// A class to hold TPC digits generated by the MC.  This inherits all of it's
/// functionality form TTPCDigit and TMCDigit.
class CP::TTPCmcDigit : public TTPCDigit, public TMCDigit {
public:

    TTPCmcDigit ();
    virtual ~TTPCmcDigit();

    /// Construct a digit for a particular channel
    TTPCmcDigit(CP::TChannelId chan, 
                short startTime, 
                std::vector<short> adcs,
                const CP::TMCDigit::ContributorContainer& contrib);

    ClassDef(TTPCmcDigit,2);
};
#endif
